#sbatch -o semixup/semixup_slurm-%A_%a.out -e semixup/semixup_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv semixup revision 0
sbatch -o ict/ict_slurm-%A_%a.out -e ict/ict_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv ict revision 0
sbatch -o pimodel/pimodel_slurm-%A_%a.out -e pimodel/pimodel_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv pimodel revision 0
sbatch -o mixmatch/mixmatch_slurm-%A_%a.out -e mixmatch/mixmatch_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv mixmatch revision 0
#sbatch -o semixup/semixup_slurm-%A_%a.out -e semixup/semixup_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv semixup revision 1
#sbatch -o ict/ict_slurm-%A_%a.out -e ict/ict_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv ict revision 1
#sbatch -o pimodel/pimodel_slurm-%A_%a.out -e pimodel/pimodel_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv pimodel revision 1
#sbatch -o mixmatch/mixmatch_slurm-%A_%a.out -e mixmatch/mixmatch_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv mixmatch revision 1
#sbatch -o semixup/semixup_slurm-%A_%a.out -e semixup/semixup_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv semixup revision 2
#sbatch -o ict/ict_slurm-%A_%a.out -e ict/ict_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv ict revision 2
#sbatch -o pimodel/pimodel_slurm-%A_%a.out -e pimodel/pimodel_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv pimodel revision 2
#sbatch -o mixmatch/mixmatch_slurm-%A_%a.out -e mixmatch/mixmatch_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv mixmatch revision 2
#sbatch -o semixup/semixup_slurm-%A_%a.out -e semixup/semixup_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv semixup revision 3
#sbatch -o ict/ict_slurm-%A_%a.out -e ict/ict_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv ict revision 3
#sbatch -o pimodel/pimodel_slurm-%A_%a.out -e pimodel/pimodel_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv pimodel revision 3
#sbatch -o mixmatch/mixmatch_slurm-%A_%a.out -e mixmatch/mixmatch_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv mixmatch revision 3
#sbatch -o semixup/semixup_slurm-%A_%a.out -e semixup/semixup_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv semixup revision 4
#sbatch -o ict/ict_slurm-%A_%a.out -e ict/ict_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv ict revision 4
#sbatch -o pimodel/pimodel_slurm-%A_%a.out -e pimodel/pimodel_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv pimodel revision 4
#sbatch -o mixmatch/mixmatch_slurm-%A_%a.out -e mixmatch/mixmatch_slurm-%A_%a.out ./scripts/sbatch_csc_ssl.sh cvgg2hv mixmatch revision 4
